version: "3.9"
services:
  nginx:
    image: nginx:mainline-alpine
    depends_on:
      - php
    ports:
      - 8080:80
    restart: always
    volumes:
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/html

  php:
    build: ./docker/php
    depends_on:
      - db
    env_file: .env
    expose:
      - 9000
    restart: always
    volumes:
      - ./src:/var/www/html

  db:
    image: mysql:8.0
    env_file: .env
    expose:
      - 3306
    hostname: $MYSQL_HOSTNAME
    ports:
      - 3306:3306
    restart: always
    volumes:
      - ./estudis.sql:/docker-entrypoint-initdb.d/estudis.sql
      - ./db_data:/var/lib/mysql

  # phpmyadmin:
  #   depends_on:
  #     - db
  #   image: phpmyadmin
  #   env_file: .env
  #   environment:
  #     PMA_HOST: $MYSQL_HOSTNAME
  #     PMA_USER: root
  #     PMA_PASSWORD: $MYSQL_ROOT_PASSWORD
  #   ports:
  #     - 8090:80
  #   restart: always