version: "3.9"
services:
  nginx:
    build: ./docker/nginx
    depends_on:
      - php
    ports:
      - 8080:80
    restart: always
    volumes:
      - ./src:/var/www/html

  php:
    build: ./docker/php
    depends_on:
      - db
    env_file: .env
    expose:
      - 9000
    restart: always
    volumes:
      - ./src:/var/www/html

  db:
    image: mysql
    env_file: .env
    expose:
      - 3306
    hostname: $MYSQL_HOSTNAME
    restart: always
    volumes:
      - ./db_data:/var/lib/mysql

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin
    env_file: .env
    environment:
      PMA_HOST: $MYSQL_HOSTNAME
      PMA_USER: root
      PMA_PASSWORD: $MYSQL_ROOT_PASSWORD
    ports:
      - 8090:80
    restart: always